export const SAVE_POSTS_LIST = 'SAVE_POSTS_LIST';
export const SAVE_PHOTOS_LIST = 'SAVE_PHOTOS_LIST';
export const SAVE_ALBULMS_LIST = 'SAVE_ALBULMS_LIST';
export const SAVE_USERS_LIST = 'SAVE_USERS_LIST';
export const SAVE_SHOWSPINNER = 'SAVE_SHOWSPINNER';
export const RESET_SHOWSPINNER = 'RESET_SHOWSPINNER';
export const SAVE_POSTDETAIL = 'SAVE_POSTDETAIL';
